### ISSUE TITLE
c.someNum points to the address space of storage variable

### ISSUE THREAD

**Issue by janbro** [pertsev/solidity_tricks#1]
The bug example in the hoisting write up is worse than your write up suggests. `c.someNum` will be pointing the storage variable `one`, meaning you could accidentally overwrite `one` if you were to attempt to set `c.someNum` to some value. To verify, call `main(0)` until `one` is equal to 10 and your proceeding calls to `main` will revert.

**Comment by pertsev** [comment]
No. The behavior you describe applies to arrays and structs only.
